### ISSUE TITLE
Investigate uBlock blocking Clade Search

### ISSUE THREAD

**Issue by i2xzy** [phylogeny-explorer/explorer#45]
**[Casey Trimm](https://github.com/c-trimm)** 24 days ago
A user reported that the ad blocker, uBlock, has blocked the clade search. Please investigate and see if this is an issue we need to be concerned with.

The user was @TSGut Timon Gutleb on Slack.

**Comment by orwell1984** [comment]
I am uBlock user and I've not seen any unwanted effects on clade search. @TSGut - can you describe how do you mean "blocked clade search"? I'll try to replicate your actions.

**Comment by TSGut** [comment]
The issue seems to be fixed now, so it might have been a uBlock Origin hickup. The problem was essentially that on multiple test browsers and devices I tried such as Chrome and Firefox the explorer search bar would not make any search recommendations and searching in general was broken. Attempts using current Chrome and uBlock Origin seem to work just fine at this moment, I'll go back and do some more testing to be sure tomorrow.

**Comment by TSGut** [comment]
I think this can be closed, it looks like the issue was with uBlock.

**Comment by orwell1984** [comment]
Thanks @TSGut
